#include<iostream>
#include"QueueDinArrIterator.h"
#include"MyException.h"

using namespace std;

int main() {
	//Printer<char> printer;
	//Queue<char> a;
	//Queue<char> b{'s', 'o'};
	//Queue<char> c{'b', 'a'};
	//Queue<char> d{'k', 'a'};
	//a = b + c;
	//a += d;
	//a.accept(printer);

	//Queue<int> a{ 1, 2, 3 };
	//Iterator<int> *it = a.createIterator();
	//while (!it->isDone()) {
	//	cout << it->currentItem() << endl;
	//	it->next();
	//}

	//Queue<int> a{1, 2, 3};
	//a.push(4);
	//a.pop();
	//a.pop();
	//a.push(5);
	//Reverser<int> reverser;
	//a.accept(reverser);
	//ReverseIterator<int> *rIt = a.createReverseIterator();
	//while (!(rIt->isDone())) {
	//	cout << rIt->currentItem() << endl;
	//	rIt->next();
	//}

	system("pause");

	return 0;
}